name: Gcp Secrets

on:
  push:
    branches:
      - main

jobs:
  terraform_run:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repos
        uses: actions/checkout@v2
      - name: setup terraform
        uses: hashicorp/setup-terraform@v1
      - name: terraform init
        run: terraform init
      - name: terraform plan
        run: terraform plan -out=tfplan
      - name: terraform apply
        run: terraform apply -auto-approve tfplan